package code;

import java.io.IOException;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.io.FloatWritable;
import org.apache.hadoop.io.IntWritable;
import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Job;
import org.apache.hadoop.mapreduce.Mapper;
import org.apache.hadoop.mapreduce.Reducer;
import org.apache.hadoop.mapreduce.lib.input.FileInputFormat;
import org.apache.hadoop.mapreduce.lib.output.FileOutputFormat;
import org.apache.hadoop.util.GenericOptionsParser;
import org.apache.log4j.PropertyConfigurator;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


public class Combiner {
	
	public static void main(String args[]) throws Exception{
		
		Configuration conf = new Configuration();
		String[] otherArgs = new GenericOptionsParser(conf, args).getRemainingArgs();
        if (otherArgs.length < 2) {
            System.err.println("Usage: hadoop jar This.jar <in> [<in>...] <out>");
            System.exit(2);
        }
        
        //Configure to have comma separator between reducer produced key and value in output file
        conf.set("mapred.textoutputformat.separator", Constant.SEP);
        
		Job job = new Job(conf);
		job.setJarByClass(Combiner.class);
		
		job.setMapperClass(TokenizerMapper.class);
		job.setMapOutputKeyClass(Text.class);
		job.setMapOutputValueClass(TempStatus.class);
		
		job.setCombinerClass(MinMaxTempCombiner.class);
		
		job.setReducerClass(MinMaxTempReducer.class);
		job.setOutputKeyClass(Text.class);
		job.setOutputValueClass(Text.class);
		
		for (int i = 0; i < otherArgs.length - 1; ++i) {
            FileInputFormat.addInputPath(job, new Path(otherArgs[i]));
        }
		FileOutputFormat.setOutputPath(job,
                new Path(otherArgs[otherArgs.length - 1]));
		System.exit(job.waitForCompletion(true) ? 0 : 1);
	}
}

/**
 * Combiner class
 * @author Darshan
 *
 */
class MinMaxTempCombiner extends Reducer<Text, TempStatus, Text, TempStatus>{

	private TempStatus tempStatus = new TempStatus();
	private static final Log LOG = LogFactory.getLog(MinMaxTempCombiner.class);
	private int combinerCallCount;
	
	public void setup(Context context) throws IOException, InterruptedException{
		
		LOG.info("Combiner is called");
		combinerCallCount = 0;
	}
	
	public void reduce(Text key, Iterable<TempStatus> values, Context context) throws IOException, InterruptedException{
		
		combinerCallCount++;
		
		float sumTMAX = 0.0f;
		int countTMAX = 0;
		float sumTMIN = 0.0f;
		int countTMIN = 0;
		
		// Iterate over data generated by Mapper
		for(TempStatus value : values){
			if(value.getTmaxCount() >= 1){
				sumTMAX += value.getTmax(); 
				countTMAX += value.getTmaxCount();
			}
			if(value.getTminCount() >= 1){
				sumTMIN += value.getTmin();
				countTMIN += value.getTminCount();
			}
		}
		
		tempStatus.setTmin(sumTMIN);
		tempStatus.setTmax(sumTMAX);
		tempStatus.setTminCount(countTMIN);
		tempStatus.setTmaxCount(countTMAX);
		
		context.write(key, tempStatus);
		
	}
	
	public void cleanup(Context context) throws IOException, InterruptedException{
		LOG.info("Number of combiner call is : "+ combinerCallCount);
	}
}
		